- name: Register the SHA of the current commit
  shell: cat REVISION
  args:
    chdir: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
  register: revision_output

- name: build and run the service defined in docker-compose.yml in the deploy_directory
  docker_service:
    project_src: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
    files: "{{ production_compose_file  }}"
    build: true
    state: present
  environment:
    TAG: "{{ revision_output.stdout }}"
