- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: create deploy user
  user: 
    name: "{{ deploy_user }}"
    shell: /bin/bash 
    groups: sudo, docker
    append: true
