- name: cloning repo
  git:
    repo: "{{ application_source_url }}"
    version: "{{ gh_branch | default('master') }}"
    dest: "{{ deploy_directory }}"
    accept_hostkey: yes
    force: yes

- name: run the service defined in docker-compose.yml in the deploy_directory
  docker_service:
    project_src: "{{ deploy_directory }}"
    build: true
