- name: cloning repo
  git:
    repo: "{{ application_source_url }}"
    version: "{{ gh_branch | default('master') }}"
    dest: "{{ deploy_directory }}"
    accept_hostkey: yes
    force: yes

- name: Register the SHA of the current commit
  shell: git log -1 --format=%h
  args:
    chdir: "{{ deploy_directory }}"
  register: git_log_output

- name: stop the service
  docker_service:
    project_src: "{{ deploy_directory }}"
    state: absent

- name: build and run the service defined in docker-compose.yml in the deploy_directory
  docker_service:
    project_src: "{{ deploy_directory }}"
    build: true
    state: present
  environment:
    TAG: "{{ git_log_output.stdout }}"
