- name: Check whether the docker-compose.yml file exists
  stat:
    path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}/docker-compose.yml"
  register: compose_file_stat

- name: stop the service
  docker_service:
    project_src: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
    state: absent
  when: compose_file_stat.stat.exists == true 
